// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/anthropic.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"anthropic-messages": {
		"claude-fable-5": object;
		"claude-fable-5-1": object;
		"claude-haiku-4-5": object;
		"claude-haiku-4-5-20251001": object;
		"claude-opus-4-5": object;
		"claude-opus-4-5-20251101": object;
		"claude-opus-4-6": object;
		"claude-opus-4-7": object;
		"claude-opus-4-8": object;
		"claude-opus-5": object;
		"claude-sonnet-4-5": object;
		"claude-sonnet-4-5-20250929": object;
		"claude-sonnet-4-6": object;
		"claude-sonnet-5": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const ANTHROPIC_MODELS: ModelCatalog<typeof modelGroups, "anthropic"> =
	flattenModelCatalog("anthropic", modelGroups);
