// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/cerebras.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"gpt-oss-120b": object;
		"qwen-3.8-27b": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const CEREBRAS_MODELS: ModelCatalog<typeof modelGroups, "cerebras"> =
	flattenModelCatalog("cerebras", modelGroups);
