// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepseek.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"deepseek-flash": object;
		"deepseek-v4-pro": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const DEEPSEEK_MODELS: ModelCatalog<typeof modelGroups, "deepseek"> =
	flattenModelCatalog("deepseek", modelGroups);
