// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/github-copilot.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"anthropic-messages": {
		"claude-fable-5": object;
		"claude-fable-5.1": object;
		"claude-haiku-4.5": object;
		"claude-opus-4.7": object;
		"claude-opus-4.8": object;
		"claude-opus-5": object;
		"claude-sonnet-4.6": object;
		"claude-sonnet-5": object;
	};
	"openai-completions": {
		"gemini-3.5-flash": object;
		"gemini-3.6-flash": object;
		"gemini-3.7-flash": object;
		"gemini-3.8-flash": object;
		"kimi-k2.7-code": object;
		"kimi-k3": object;
	};
	"openai-responses": {
		"gpt-5-mini": object;
		"gpt-5.3-codex": object;
		"gpt-5.4": object;
		"gpt-5.4-mini": object;
		"gpt-5.4-nano": object;
		"gpt-5.5": object;
		"gpt-5.6-luna": object;
		"gpt-5.6-sol": object;
		"gpt-5.6-terra": object;
		"gpt-6-astra": object;
		"grok-4.5": object;
		"grok-4.6": object;
		"mai-code-1-flash-picker": object;
		"mai-code-1.1-flash": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const GITHUB_COPILOT_MODELS: ModelCatalog<typeof modelGroups, "github-copilot"> =
	flattenModelCatalog("github-copilot", modelGroups);
