// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/google.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"google-generative-ai": {
		"deep-research-max-preview-04-2026": object;
		"deep-research-preview-04-2026": object;
		"gemini-2.5-computer-use-preview-10-2025": object;
		"gemini-2.5-flash": object;
		"gemini-2.5-flash-lite": object;
		"gemini-2.5-pro": object;
		"gemini-3-flash-preview": object;
		"gemini-3.1-flash-lite": object;
		"gemini-3.1-flash-lite-image": object;
		"gemini-3.1-flash-lite-preview": object;
		"gemini-3.1-flash-live-preview": object;
		"gemini-3.1-pro-preview": object;
		"gemini-3.1-pro-preview-customtools": object;
		"gemini-3.5-flash": object;
		"gemini-3.5-flash-lite": object;
		"gemini-3.6-flash": object;
		"gemini-3.7-flash": object;
		"gemini-3.8-flash": object;
		"gemini-flash-latest": object;
		"gemini-flash-lite-latest": object;
		"gemma-4-26b-a4b-it": object;
		"gemma-4-31b-it": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const GOOGLE_MODELS: ModelCatalog<typeof modelGroups, "google"> =
	flattenModelCatalog("google", modelGroups);
