// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/huggingface.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"MiniMaxAI/MiniMax-M2": object;
		"MiniMaxAI/MiniMax-M2.1": object;
		"MiniMaxAI/MiniMax-M2.5": object;
		"MiniMaxAI/MiniMax-M2.7": object;
		"MiniMaxAI/MiniMax-M3": object;
		"Qwen/Qwen2.5-Coder-32B-Instruct": object;
		"Qwen/Qwen3-235B-A22B": object;
		"Qwen/Qwen3-235B-A22B-Instruct-2507": object;
		"Qwen/Qwen3-235B-A22B-Thinking-2507": object;
		"Qwen/Qwen3-30B-A3B": object;
		"Qwen/Qwen3-32B": object;
		"Qwen/Qwen3-Coder-30B-A3B-Instruct": object;
		"Qwen/Qwen3-Coder-480B-A35B-Instruct": object;
		"Qwen/Qwen3-Coder-Next": object;
		"Qwen/Qwen3-Next-80B-A3B-Instruct": object;
		"Qwen/Qwen3-Next-80B-A3B-Thinking": object;
		"Qwen/Qwen3-VL-235B-A22B-Instruct": object;
		"Qwen/Qwen3-VL-235B-A22B-Thinking": object;
		"Qwen/Qwen3.5-122B-A10B": object;
		"Qwen/Qwen3.5-27B": object;
		"Qwen/Qwen3.5-35B-A3B": object;
		"Qwen/Qwen3.5-397B-A17B": object;
		"Qwen/Qwen3.5-9B": object;
		"Qwen/Qwen3.6-27B": object;
		"Qwen/Qwen3.6-35B-A3B": object;
		"Qwen/Qwen3.8-2.4T-A95B": object;
		"Qwen/Qwen3.8-27B": object;
		"XiaomiMiMo/MiMo-V2-Flash": object;
		"XiaomiMiMo/MiMo-V2.5": object;
		"XiaomiMiMo/MiMo-V2.5-Pro": object;
		"deepseek-ai/DeepSeek-R1": object;
		"deepseek-ai/DeepSeek-R1-0528": object;
		"deepseek-ai/DeepSeek-V3": object;
		"deepseek-ai/DeepSeek-V3-0324": object;
		"deepseek-ai/DeepSeek-V3.1": object;
		"deepseek-ai/DeepSeek-V3.2": object;
		"deepseek-ai/DeepSeek-V4-Flash": object;
		"deepseek-ai/DeepSeek-V4-Flash-0731": object;
		"deepseek-ai/DeepSeek-V4-Flash-Vision-Exp": object;
		"deepseek-ai/DeepSeek-V4-Pro": object;
		"deepseek-ai/DeepSeek-V4-Pro-0813": object;
		"deepseek-ai/DeepSeek-V4.1-Flash": object;
		"google/gemma-3-12b-it": object;
		"google/gemma-3-27b-it": object;
		"google/gemma-3-4b-it": object;
		"google/gemma-4-26B-A4B-it": object;
		"google/gemma-4-31B-it": object;
		"meta-llama/Llama-3.1-8B-Instruct": object;
		"meta-llama/Llama-3.3-70B-Instruct": object;
		"moonshotai/Kimi-K2-Instruct": object;
		"moonshotai/Kimi-K2-Instruct-0905": object;
		"moonshotai/Kimi-K2-Thinking": object;
		"moonshotai/Kimi-K2.5": object;
		"moonshotai/Kimi-K2.6": object;
		"moonshotai/Kimi-K2.7-Code": object;
		"moonshotai/Kimi-K3": object;
		"openai/gpt-oss-120b": object;
		"openai/gpt-oss-20b": object;
		"stepfun-ai/Step-3.5-Flash": object;
		"stepfun-ai/Step-3.7-Flash": object;
		"tencent/Hy3": object;
		"thinkingmachines/Inkling": object;
		"thinkingmachines/Inkling-Small": object;
		"zai-org/GLM-4.5": object;
		"zai-org/GLM-4.5-Air": object;
		"zai-org/GLM-4.5V": object;
		"zai-org/GLM-4.6": object;
		"zai-org/GLM-4.6V-Flash": object;
		"zai-org/GLM-4.7": object;
		"zai-org/GLM-4.7-Flash": object;
		"zai-org/GLM-5": object;
		"zai-org/GLM-5.1": object;
		"zai-org/GLM-5.2": object;
		"zai-org/GLM-5.3": object;
		"zai-org/GLM-5.3-Flash": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const HUGGINGFACE_MODELS: ModelCatalog<typeof modelGroups, "huggingface"> =
	flattenModelCatalog("huggingface", modelGroups);
