// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xai.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-responses": {
		"grok-4.3": object;
		"grok-4.5": object;
		"grok-4.6": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const XAI_MODELS: ModelCatalog<typeof modelGroups, "xai"> =
	flattenModelCatalog("xai", modelGroups);
