// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/xiaomi-token-plan-sgp.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"mimo-v2.5": object;
		"mimo-v2.5-pro": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const XIAOMI_TOKEN_PLAN_SGP_MODELS: ModelCatalog<typeof modelGroups, "xiaomi-token-plan-sgp"> =
	flattenModelCatalog("xiaomi-token-plan-sgp", modelGroups);
